# Generated by Django 4.2.7 on 2023-11-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('type_variable_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('sponsor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('sponsor_id', models.IntegerField()),
                ('invoce_id', models.IntegerField()),
                ('state_paid', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('paid', models.IntegerField()),
                ('value', models.IntegerField()),
                ('code_currency_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('sponsor_id', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('type_variable_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('sponsor_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('strategic_line_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlannItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('sponsor_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('plan_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.planitem')),
                ('service_planning_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.serviceplanning')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReferenceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('user_rol_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('payment_reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentreference')),
                ('service_planning_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.serviceplannitem')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('value', models.IntegerField()),
                ('Payment_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentagreement')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAgreementConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('value', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('concept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.concept')),
                ('payment_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentagreement')),
            ],
        ),
        migrations.AddField(
            model_name='paymentagreement',
            name='payment_frencuency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentfrequency'),
        ),
        migrations.AddField(
            model_name='paymentagreement',
            name='payment_reference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentreference'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField()),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('code', models.IntegerField()),
                ('user_email', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('state_transaction', models.BooleanField()),
                ('paid', models.IntegerField()),
                ('code_currency', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('Payment_Reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.paymentreference')),
            ],
        ),
    ]
