# Generated by Django 4.2.6 on 2023-11-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_Reference_id',
            new_name='payment_reference_id',
        ),
    ]
